### Workshop 3


##Matrices
matr <- matrix(seq(from = 1, to = 6, by = 1), ncol = 3, nrow = 2)
#Look at matrix
matr

#Gives 3x2 matrix, using a sequence generated by the seq() function.

#Creating a blank matrix full of NAs
matrix(NA, ncol = 3, nrow = 4)

#You can also shape a vector into a matrix using the dim() function:
b <- seq(from = 1, to = 6, by = 1)
#Set the dimensions of the matrix (nrows and then ncolumns)
dim(b) <- c(2, 3)
##look at the matrix
b

# dim() can also be used to show us the properties of a matrix - 
#i.e. its dimensions - returned as no. of rows in the matrix first, and no. of columns second.
#: between two numbers means "generate a sequence of whole numbers from x to y"

##make a matrix and look at the dimensions
dim(matrix(1:6, ncol = 3, nrow = 2))
#gives 2, 3



##Task
#Make matrix of 80 random numbers with normal distribution.
#Using rnorm()
matrix(rnorm(n = 80, sd = 2, mean = 20), ncol = 5, nrow = 16)



#Values stored in matrices can be accessed using the [ ] operator
#We give two values - the first determines the row that R should look in, the second determines the column 

#Make a matrix and look at it
our_matrix <- matrix(6:1, ncol = 3, nrow = 2)
our_matrix
#Return the value of the matrix in the first row and the second column
our_matrix[1, 2]

#Can also return multiple values
#Return the values in the first row from the first and second column:
our_matrix[1,c(1,2)]

#Return the values in the first row
our_matrix[1,]
#Return the values in the second column
our_matrix[,2]




## Matrix operations
#Matrices can be added, subtracted, multiplied, and divided by one another, 
#whether that is a two dimensional matrix or a one dimensional vector. 
#These are specificed through the normal operators (+, -, etc)

#a matrix of values:
init_mat <- matrix(1:6, ncol=3, nrow=2)
#add 1 to all of the values
init_mat+1

#R approaches matrix multiplication depending on how you specify the multiplication 
#if you use the * symbol, R will perform element-wise multiplication
#for true matrix multiplication, need special operator %*%

#Can use function rep() to repeat a sequence of numbers
#e.g.:
mat_rep <- matrix(rep(1:3, each = 5), nrow = 3, ncol = 5, byrow = TRUE)
mat_rep

#multipyling 2 matrices using element-wise multiplication
vec_seq <- 1:5 #1D matrix
mat_rep * vec_seq
# This multiplies the 1st number in the vector with the 1st number in column one, the 2nd number in the vector by the 2nd number in column 1, etc
# Then rolls over from bottom of column 1 to the top of column 2 and so on.




## Matrix multiplication
#A matrix:
mat_seq <- matrix(seq(from = 1, to = 20, length.out = 6), ncol = 3, nrow = 2)

#A vector to multiply by:
vec_seq <- seq(from = 10, to = 4, length.out = 3)

#Multiply the matrices using element-wise multiplication
mat_seq %*% vec_seq
#Gives us the 1 x 2 matrix we expect given the rules of matrix multiplication.




#Data in matrices
#As with vectors matrices can include numeric or character strings, or a mix, and we can also perform logial operators on them:
  
#Make a matrix 
mat_seq <- matrix(seq(1, 20, length.out = 6), ncol=3, nrow=2)
mat_seq

#Display the logical operator of this matrix for values greater than 10
mat_seq > 10
#Gives matrix of Trues and Falses

#Return the values which are greater than 10
mat_seq[mat_seq > 10]

#Values returned in the form of a vector in the order they were found in the matrix (top left, down columns left to right)

#List of matrices functions on worksheet 3, 2.1.3


##Arrays
#Probably won't need

#Making a simple array:
this_is_an_array <- array(1:24, dim=c(3,4,2))
#here, dimensions defined are 3 rows, 4 columns, 2 matrix levels
this_is_an_array

#arrays are also n dimensional
still_an_array <- array(1:24, dim = c(3,2,2,4))
dim(still_an_array)
#we have 8 small matrices, in two large groups (numbered 1 and 2) 
#and four groups in each of those large groups (numbered 1:4).



##Task
# array of 100 numbers in uniform distribution (runif()) with at least 3 groups.
task_array <- array(runif(n = 100, min = 1, max = 500), dim = c(5,5,4))
task_array


### Data frames
#Data frames allow us to store multiple different types of data in the same data structure and work with it.
#We can create data frames using the data.frame() function as follows:

#Make a data frame with information on whether a Species was seen (1 = yes, 0 = no), on a particular Day:
our_data <- data.frame("Day" = rep(1:3, each = 3), 
                       "Species" = rep(letters[1:3], each = 3),
                       "Seen" = ?rbinom(n = 9, size = 1, prob = 0.5))
our_data

#Look at the Day column
our_data["Day"] 

#we can also access the data via the $ operator:
our_data$Day
#We can also use the $ operator to add a column to a data.frame.
##add a new column called location
our_data$location <- "United Kingdom"
#if we just provide a single value (“United Kingdom”) R will assume we want this repeated in ever row of the column automatically.


## Calculations using data.frame values

#We can use the data in data.frames exactly as if they were vectors accessing them using the $ operator:
#Some simple data
simple_data  <- data.frame( "a" = runif(10, 0, 1), 
                            "b" =  rnorm(10, 3, 5))

#Example calculations
simple_data$calc <- (simple_data$a * simple_data$b) - simple_data$b
simple_data



## Task

task_df <- data.frame("name" = c('Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'),
"score" = c(12.5, 9, 16.5, 12, 9, 20, 14.5, 13.5, 8, 19),
"questions" = c(1, 3, 2, 3, 2, 3, 1, 1, 2, 1),
"qualify" = c('yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'))

str(task_df)
#Shows the structure of the dataframe

task_df$mean_score <- task_df$score/task_df$questions
#Adds mean score column, which contains score divided by questions
task_df



### Lists
#Can contain multiple data types and multiple objects e.g. data frames, matrices and vectors.
#Created using list() function.

#Code below makes a list containing 4 objects:
#make a numeric matrix
num_mat <- matrix(rep(1:3, each = 5), 
                  nrow = 3, 
                  ncol = 5, 
                  byrow = TRUE)

#and a vector of letters
let_vec <- LETTERS[4:16]

#and a data.frame of species information:
species_dat <- data.frame("Species" = c("a", "b"), 
                          "Observed" = c(TRUE, FALSE)) 

#save them into a list using the list() function
our_list <- list(num_mat, 
                 let_vec,
                 species_dat, 
                 5)

#view the list
our_list

# We can use a double square brackets to extract these objects from the list:
#extracting the first object
our_list[[1]]

# Extract the first row of the 3rd object in the list:
our_list[[3]][1,]


#Can also save objects into a list names, using "" as in data frames:
our_list <- list("numbers_vec" = num_mat, 
                 "letters" = let_vec,
                 "spp_pres" = species_dat, 
                 "number" = 5)

#Display the names of the Objects:
names(our_list)

#View an object
our_list$spp_pres
